hotg-ai/rune

.github/workflows/main.yml, README.md
Now the repo is public we can use GitHub Pages to host the nightly API docs.
=> Upload API docs to GitHub Pages

Cargo.lock, codegen/src/lib.rs, codegen/tests/smoke_test.rs, ffi/tests/run_cxx_example.rs, rune/Cargo.toml, rune/build.rs, rune/src/build.rs, rune/src/main.rs, rune/src/version.rs
When linking to `runic_types` and our various proc blocks we used to *only* use path dependencies. This required the user to be inside a checkout of the `hotg-ai/rune` repository.
With this PR, we now fall back to using git dependencies if the path dependency isn't available, checking out the *exact* commit that the `rune` binary was compiled to. This is an interim measure until `runic_types` and our proc blocks are released on crates.io.
Because we now embed build information in the binary, I've updated our `rune --version` command to behave more like `rustc --version` and `rustc --version --verbose`.
```console
$ rune -V
rune 0.2.1 (4c85065 2021-04-19)
$ rune -Vv 
rune 0.2.1 (4c85065 2021-04-19)
binary: rune
rune-version: 0.2.1
commit-hash: 4c8506555a20bd8fbfcdcb56cc57e0f4292e16bb …
```
=> Make "rune build" link to rune crates via git if they aren't available on disk

Cargo.lock, codegen/src/lib.rs, rune/Cargo.toml, rune/src/build.rs, rune/src/version.rs
This was originally triggered by [a conversation](https://hotg-ai.slack.com/archives/C01B8R53ZPV/p1619315411095100) with @kthakore on Slack. It now lets users of `rune-codegen` specify the Rune project's git repo via a commit, tag, or branch, not just commit.
@kthakore as a note, I'm not sure whether you'll want to be specifying the `master` branch here. If you do that, `hammerd` will always be using the latest and greatest Rune instead of a version it was tested with. I could see a scenario where the Rune project's `master` branch gets accidentally broken for a couple days (I dunno, say Michael side-stepped our CI and committed pushed to `master`, and now `runic-types` doesn't compile) and that causes all instances of `hammerd` to not be able to build runes or proc blocks.
If you want to …
=> Allow specifying the Rune project location in more fine-grained detail

xtask/src/dist.rs
It looks like [`strip` failed on the Mac nightly build](https://github.com/hotg-ai/rune/runs/2456488163?check_suite_focus=true). Having stripped binaries is mainly a convenience, so if it fails we should just log a warning and keep going.
=> Strip failures should be non-fatal

codegen/src/lib.rs, codegen/tests/smoke_test.rs
@meelislootus this fixes your issue where the `noise-filtering` proc block has a hyphen and our `rune-codegen` tries using that as the proc block's namespace.
```
Meeliss-MacBook-Pro-3:rune meelislootus$ ./target/debug/rune build ./examples/microspeech/Runefile 
[2021-05-07T14:28:38.890Z DEBUG rune::build] Parsing "./examples/microspeech/Runefile"
[2021-05-07T14:28:38.891Z DEBUG rune::build] Compiling microspeech in "/Users/meelislootus/Library/Caches/runes/microspeech"
[2021-05-07T14:28:38.913Z DEBUG rune_codegen] Executing "cargo" "+nightly" "build" "--target=wasm32-unknown-unknown" "--quiet" "--release"
error[E0425]: cannot find value `noise` in this scope
--> lib.rs:22:31
|
22 |   let mut noise_filtering = noise-filtering::NoiseFiltering::default();
|                ^^^^^ not found in …
```
=> Type names in generated Rust code can't contain hyphens

codegen/src/lib.rs, examples/person_detection/Runefile, proc_blocks/ohv_label/src/lib.rs, rune/src/run.rs, rune/tests/integration.rs, runic-types/src/lib.rs, runtime/src/common_capabilities/image.rs, runtime/src/common_capabilities/mod.rs, syntax/src/yaml/analysis.rs, xtask/src/main.rs
This PR lets you use arbitrary, unescaped, Rust expressions as an argument's value.
The idea is we add a new `PixelFormat` enum to `runic-types` which then gets brought into scope via [our existing glob import](https://github.com/hotg-ai/rune/blob/99059c202fcd854cc944a42b0ae95146ceaa09c5/codegen/src/boilerplate/lib.rs.hbs#L8). This `PixelFormat` enum can be freely converted into a `runic_types::Value`, the primitive type used to pass values back and forth between a Rune and the runtime.
Whenever `rune-codegen` sees a string argument that starts with `@`, instead of quoting the argument it will paste the text in verbatim. That means when you have `--pixel-format PixelFormat::GrayScale` in your Runefile we'll generate `image.set_parameter("pixel_format", PixelFormat::RGB)`. This then gets …
=> Allow arbitrary Rust expressions as part of capability/proc block arguments

.github/workflows/main.yml, .github/workflows/nightly.yml
It looks like the nightly build has been failing over the weekend because we'd generate a wheel but our sanity check (install the newly generated wheel and import it) failed.
Annotated output from [a failing build](https://github.com/hotg-ai/rune/runs/2592560410?check_suite_focus=true).
```console
$ maturin build --manifest-path python/Cargo.toml \
--bindings pyo3 \
--manylinux off \
--no-sdist \
--release
Compiling rune_py v0.1.0 (/home/runner/work/rune/rune/python)
Finished release [optimized] target(s) in 54.67s
📦 Built wheel for abi3 Python ≥ 3.6 to /home/runner/work/rune/rune/target/wheels/rune_py-0.1.0-cp36-abi3-linux_x86_64.whl
$ pip install target/wheels/*.whl
Processing ./target/wheels/rune_py-0.1.0-cp36-abi3-linux_x86_64.whl
Collecting numpy~=1.15
Downloading …
```
=> Troubleshoot Nightly Wheel Issues

proc_blocks/fft/src/lib.rs, proc_blocks/fft/src/macros.rs, proc_blocks/noise-filtering/src/gain_control.rs, proc_blocks/noise-filtering/src/lib.rs, proc_blocks/noise-filtering/src/macros.rs
This is just finishing off the work that was done in #158. We switched from generating `my_proc_block.with_count()` builder method calls for setting properties (`count`, in this case) over to `my_proc_block.set_count()` setters and this just removes the last of the builder methods now they are no longer needed.
=> Removed all proc block builder methods in favour of setters

codegen/src/environment.rs
We only run `cargo fmt` on the generated code as a convenience for anyone that may want to read the source code. We don't care if it fails because the `rustfmt` component isn't installed.
Fixes #172.
=> Swallow output from "cargo fmt" during "rune build"

rune/src/run.rs
This updates the `rune run` subcommand to make capabilities more discoverable. People can still use the `--capability image:person.png` syntax if they want, but we'd prefer them to use `--image person.png`.
The updated help text:
```console
$ rune run -h
Run a rune
USAGE:
rune run [OPTIONS] <rune>
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
--accelerometer <accelerometer>...    A CSV file containing [X, Y, Z] vectors to be returned by the ACCEL
capability
-c, --capability <capabilities>...        Initialize capabilities based on `key:value` pairs. Prefer to use aliases
like "--image" and "--sound" when the capability is builtin
--image <image>...                    An image to be returned by the IMAGE capability
--random <random> …
```
=> Added aliases for providing capabilities to the rune CLI

.github/workflows/main.yml
Whenever we merge new code into `master`, the API docs build fails with an odd error. Hopefully by moving the `cargo doc` step to its own job it won't be contaminated by anything else and will be able to clear its cache (or whatever is breaking things). 
```
Documenting rune-wasmer-runtime v0.1.0 (/home/runner/work/rune/rune/wasmer-runtime)
Running `rustdoc --edition=2018 --crate-type lib --crate-name rune_wasmer_runtime wasmer-runtime/src/lib.rs -o /home/runner/work/rune/rune/target/doc --error-format=json --json=diagnostic-rendered-ansi -L dependency=/home/runner/work/rune/rune/target/debug/deps --extern anyhow=/home/runner/work/rune/rune/target/debug/deps/libanyhow-9787f58e2a6422c5.rmeta --extern log=/home/runner/work/rune/rune/target/debug/deps/liblog-3537f742ccc95852.rmeta --extern …
```
=> Moved the generation of API docs to its own job

Cargo.lock, codegen/src/code.rs, codegen/src/lib.rs, rune/Cargo.toml, rune/src/inspect.rs, rune/src/main.rs, rune/src/model_info.rs, rune/src/version.rs, syntax/src/hir.rs
Continuing from #166, this adds a `rune inspect sine.rune` sub-command that lets you find out more about a Rune, in particular the Capabilities it uses.
```console
$ rune inspect person_detection.rune
Compiled by: rune v0.2.1 (c846a5b 2021-05-27)
Capabilities:
image (Image)
Outputs:
- u8[1, 96, 96]
Parameters:
- height: Int(96)
- width: Int(96)
- pixel_format: String("@PixelFormat::GrayScale")
```
There is also a much richer JSON format you can use:
```console
$ rune inspect person_detection.rune --format json
{
"build_info": {
"timestamp": "2021-05-27T22:21:29.802283431Z",
"profile": "debug",
"optimization_level": 0,
"crate_info": {
"name": "rune",
"version": "0.2.1",
"authors": [
"Kartik Thakore <kartik@thakore.ai>",
"Akshay Sharma <akshay@sharma.ai>",
"Michael-F-Bryan …
```
=> Add a "rune inspect" subcommand for inspecting runes

Cargo.lock, proc_blocks/image-normalization/Cargo.toml, proc_blocks/image-normalization/src/distribution.rs, proc_blocks/image-normalization/src/lib.rs, python/Cargo.toml, python/src/proc_blocks/image_normalization.rs, python/src/proc_blocks/mod.rs, python/tests/integration_tests.py, runic-types/src/lib.rs, runic-types/src/tensor.rs
=> Image Normalization

.github/workflows/nightly.yml
I've noticed that we are generating new nightly releases even when there have been no new code changes. If possible, I'd like to avoid this because it uses up CI time and gives people the impression that work has been done when there hasn't... plus the daily notifications are kinda annoying.
=> Troubleshoot unnecessary nightly releases

.github/workflows/main.yml
Sometimes generating docs on GitHub actions will spuriously fail with a random "file not found" error - possibly due to caching. This adds an extra step to the API generation job which will automatically delete the docs generated so far and try again.
```
error: failed to remove file `/home/runner/work/rune/rune/target/doc/rune/constant.DEFAULT_RUST_LOG.html`
Caused by:
No such file or directory (os error 2)
```
=> Spurious failures generating API docs in CI

.github/workflows/nightly.yml
The "don't make a new release if there were no code changes" check wasn't working before because we didn't do a full clone of the repository in the `check_date` job. That meant we'd never see the previous `nightly` tag and think we need to make a new release.
=> Stop making unnecessary GitHub Releases

.cargo/config.toml, Cargo.lock, codegen/src/environment.rs, codegen/src/lib.rs, ffi/tests/run_cxx_example.rs, rune/src/build.rs, rune/src/main.rs
In #202, @Mi1ind mentioned that we need some sort of progress indicator to let users know `rune` is waiting for `cargo` to finish compiling and hasn't just crashed.
I've altered the command line interface to behave more like `cargo`:
- building normally shows some general output
- using `--quiet` hides everything
- using `--verbose` shows all the `cargo` and `rustc` calls in explicit detail
The output from `rune build` now looks like this...
<details>
<summary>Building Normally</summary>
```console
$ rune build examples/noop/Runefile.yml
[2021-06-22T14:17:59.654Z INFO  rune_codegen::environment] Generating the project in "/home/michael/.cache/runes/noop"
Updating crates.io index
Compiling proc-macro2 v1.0.27
Compiling unicode-xid v0.2.2
Compiling syn v1.0.73
Compiling serde_derive …
```
=> Provide more fine-grained control over sub-command output

Cargo.lock, crates/rune-cli/Cargo.toml, crates/rune-cli/benches/rune_benchmark.rs, crates/rune-cli/src/lib.rs, crates/rune-cli/src/run/mod.rs
We use the criterion benchmark framework for this task, as the built in rust benchmarks aren't yet available in rust stable.
Each of the benchmarks use a sample size of 10 instead of the default 100.
These benchmarks measure the time taken for:
1) build - sine rune
2) inference - sine rune, microspeech, style transfer.
The results on my Linux Ryzen 7 1700 machine look like:
~TODO: Try to enable Github Actions for these benchmarks~ These benchmarks can be run manually before each release, so we aren't adding them to github actions for now
=> Initial implementation benchmarks for the rune cli

rust-toolchain.toml
This should fix an ICE (rust-lang/rust#87877) we found in our nightly releases.
=> Bumped the nightly version because of rust-lang/rust#87877

bindings/native/BUILD.md
The package was renamed from `rune-native` to `hotg-rune-native`, which made the commands fail with an odd error (`error: cannot specify features for packages outside of workspace`)
=> Fix `hotg-rune-native` build instructions

Cargo.lock, Cargo.toml, crates/wasm3-runtime/src/lib.rs, crates/wasm3-runtime/tests/integration.rs, images/runicos-base/runtime/src/image/wasm3_impl.rs
This is just #275 but with the merge conflicts resolved.
=> wasm3: propagate host errors as WASM abort traps

CHANGELOG.md, Cargo.lock, Cargo.toml, bindings/native/Cargo.toml, bindings/python/Cargo.toml, crates/codegen/Cargo.toml, crates/codegen/src/manifest.rs, crates/rune-cli/Cargo.toml, crates/rune-core/Cargo.toml, crates/runtime/Cargo.toml, crates/syntax/Cargo.toml, crates/wasm3-runtime/Cargo.toml, crates/wasmer-runtime/Cargo.toml, crates/xtask/Cargo.toml, crates/xtask/src/main.rs, images/runicos-base/runtime/Cargo.toml, images/runicos-base/wasm/Cargo.toml, integration-tests/Cargo.toml, proc-blocks/audio_float_conversion/Cargo.toml, proc-blocks/fft/Cargo.toml, proc-blocks/image-normalization/Cargo.toml, proc-blocks/label/Cargo.toml, proc-blocks/macros/Cargo.toml, proc-blocks/modulo/Cargo.toml, proc-blocks/most_confident_indices/Cargo.toml, proc-blocks/noise-filtering/Cargo.toml, proc-blocks/normalize/Cargo.toml, proc-blocks/proc-blocks/Cargo.toml
Now WASM3 has put out another release we can remove the temporary `[patch]` introduced in #275 and put out a release.
=> Cut the next release

CHANGELOG.md, crates/rune-cli/src/inspect.rs
=> rune inspect fails when no git version metadata is present

CHANGELOG.md, crates/rune-cli/src/graph.rs, crates/rune-cli/src/inspect.rs, crates/rune-cli/src/run/command.rs, crates/rune-cli/src/run/mod.rs, crates/rune-cli/src/run/resources.rs
Because of the way `wasmparser`'s `Parser::parse_all()` method is implemented, triggering a "bad magic number" error won't let the parser make any progress, meaning if you *don't* `break` on errors you'll get an infinite iterator. 
Later on we skip any errors and try to iterate over every `Payload` in the infinite iterator, causing commands like `rune inspect` and `rune run` to run forever.
Fixes #315.
=> Reading metadata from a non-WebAssembly file creates an infinite iterator

.github/workflows/releases.yml
It looks like we accidentally removed this when using GitHub's Docker registry, but we actually need it in order to upload a new `tinyverseml/rune-cli` image.
=> Log in to DockerHub before building and pushing

Cargo.lock, crates/compiler/src/codegen/generate_rune_graph_section.rs, crates/rune-cli/src/lib.rs, crates/rune-core/src/lib.rs, crates/rune-core/src/pipelines.rs, examples/debugging/identity/src/lib.rs, images/runicos-base/wasm/src/model.rs, images/runicos-base/wasm/src/serial.rs, integration-tests/compile-pass/proc-block-with-multiple-inputs-and-outputs/identity/src/lib.rs, proc-blocks/audio_float_conversion/Cargo.toml, proc-blocks/audio_float_conversion/src/lib.rs, proc-blocks/fft/Cargo.toml, proc-blocks/fft/src/lib.rs, proc-blocks/image-normalization/Cargo.toml, proc-blocks/image-normalization/src/lib.rs, proc-blocks/label/Cargo.toml, proc-blocks/label/src/lib.rs, proc-blocks/modulo/src/lib.rs, proc-blocks/most_confident_indices/Cargo.toml, proc-blocks/most_confident_indices/src/lib.rs, proc-blocks/noise-filtering/Cargo.toml, proc-blocks/noise-filtering/src/gain_control.rs, proc-blocks/noise-filtering/src/lib.rs, proc-blocks/noise-filtering/src/noise_reduction.rs, proc-blocks/normalize/src/lib.rs, proc-blocks/proc-blocks/src/lib.rs
We originally used this as a way to check that a particular node was being given an appropriate input tensor and so capabilities know what dimensions to use.
However, we now accept multiple inputs, which the `HasOutputs` method signature doesn't allow. We've also updated the generated code so capabilities are given their output dimensions [as part of the construction process](https://github.com/hotg-ai/rune/blob/174ffae7e18a9942dde41ccce46596af4412f83e/images/runicos-base/wasm/src/capability.rs#L13).
This is part of the overall process of simplifying proc blocks (see #328).
=> Removed the unnecessary HasOutputs trait

CHANGELOG.md, bindings/web/src/Runefile.ts, crates/compiler/runefile-schema.json, crates/compiler/src/codegen/generate_lib_rs.rs, crates/compiler/src/lowering/components.rs, crates/compiler/src/lowering/register_stages.rs, crates/compiler/src/parse/yaml.rs, crates/compiler/src/type_check/mod.rs, crates/compiler/src/type_check/model_args_are_consumed.rs, crates/rune-core/src/lib.rs, integration-tests/compile-fail/unknown-model-format/Runefile.yml, integration-tests/compile-fail/unknown-model-format/expected.stderr, integration-tests/compile-pass/model-arguments-should-be-used/Runefile.yml, integration-tests/compile-pass/model-arguments-should-be-used/warning.stderr
This gives model nodes an `args` field which is essentially a `HashMap<String, String>`. 
We also let the user specify a `format` to indicate the format this model is in (e.g. `tensorflow-lite`, `tensorflow`, or `onnx`) so that information can be passed on to the runtime using our "mimetype" mechanism. If no `format` is provided, it will default to `tensorflow-lite`.
I've added a lint which warns if any arguments in the model's `args` dictionary haven't been consumed during the lowering process. That should help people to detect typos or when they are using a Runefile with proprietary extensions with the open-source `rune` CLI.
@aminhotg, @f0rodo, and @jacekpie, [this integration test](https://github.com/hotg-ai/rune/blob/c4d9c54ff81a431bfaec7a0404ad6104069a3535/integration-tests/compile-f …
=> Let models have an "args" dictionary to specify the model format

bindings/web/package.json, bindings/web/src/facade.ts
After reading https://github.com/tensorflow/tfjs/issues/206, it doesn't seem like tf.js supports `uint8` tensors. As a workaround, let's let people return either a tensor *or* a raw byte buffer that will be blindly copied across.
=> Allow ReadInput to return either a Tensor or a raw byte array

.github/workflows/main.yml, .github/workflows/releases.yml
CI is failing for the Rune project due to a bug in one of our dependencies (https://github.com/hotg-ai/librunecoral/issues/43). As a hacky temporary workaround, this PR disables the MacOS builds so we can keep merging changes.
=> Disable MacOS builds

bindings/web/rune/package.json, bindings/web/rune/src/Tensor.ts
The [release notes](https://developer.apple.com/safari/technology-preview/release-notes/#r121) for Safari version 121 say that `BigUint64Array` and `BigInt64Array` are supported ([caniuse says it was released in October 2021](https://caniuse.com/mdn-javascript_builtins_bigint64array_bigint64array)), but in practice we've found Safari browsers where they aren't defined. 
To avoid a `ReferenceError` on these browsers we can use a shim class which will throw an exception whenever you try to construct these unsupported types. According to https://github.com/zloirock/core-js/issues/381 and [the `core-js` README](https://github.com/zloirock/core-js#missing-polyfills) it isn't possible to polyfill bigint, so this is probably the best we can do.
Fixes #412.
=> Added a workaround for Safari and BigUint64Array

Cargo.lock, crates/compiler/src/codegen/generate_rust_toolchain_toml.rs, crates/compiler/src/lib.rs, crates/compiler/src/toolchain.rs, crates/proc-blocks/src/descriptor.rs, crates/rune-cli/Cargo.toml, crates/rune-cli/src/build.rs, crates/rune-cli/src/inspect/mod.rs, crates/rune-cli/src/inspect/proc_block.rs, crates/rune-cli/src/inspect/rune.rs
This modifies the existing `rune inspect` command so when you point it at a crate's folder on disk it will compile the crate to WebAssembly and extract the proc-block metadata.
Here is an example of what you might get if you ask for JSON output:
```console
$ cargo rune inspect ~/Documents/hotg-ai/proc-blocks/audio_float_conversion --format=json
{
"type_name": "AudioFloatConversion",
"description": "Convert a PCM audio clip from 16-bit signed integers to floats between 0 and\n1.",
"available_transforms": [
{
"inputs": [
{"element_type": "I16", "dimensions": "Arbitrary"}
],
"outputs": [
{"element_type": "F32", "dimensions": "Arbitrary"}
]
}
]
}
$ cargo rune inspect ~/Documents/hotg-ai/proc-blocks/audio_float_conversion --format=text
AudioFloatConversion
--------------------
Convert a PCM …
```
=> Command for "rune inspect proc-block"

Cargo.lock, crates/compiler/Cargo.toml
Hi! I am the author of the `jsonschema` crate you're using.
It seems you were not affected by the recent compilation issues in the `0.15.x` series, but I thought that I'll submit a PR that bumps `jsonschema` to its latest version anyway :) Hope it is ok
=> chore: Update `jsonschema` to `0.16.0`
